pipeline:
  estimator:
    type:               "EKF"
    file:               "ekf_full_no_imu.yaml"

  sampler:
    type:               "Time"

  controller:
    type:               "GEO"
    file:               "geo.yaml"

  bridge:
    type:               "SBUS"
    file:               "volley_sbus.yaml"

quadrotor:              "volley_drone.yaml"

dt_min:                 0.01    # 0.00333 when PID or INDI are used
dt_telemetry:           0.1  # Publish telemetry messages with this period (used for GUI and IMU)

traj_type:              "poly_min_snap"
velocity_in_bodyframe:  false
takeoff_height:         1.0   # target takeoff height
takeoff_threshold:      0.5   # height under which takeoff is performed
start_land_speed:       0.6
brake_deceleration:     5.0
go_to_pose_mean_vel:    1.5
stop_after_feedthrough: true
feedthrough_timeout:    0.1

#trajectory_visualization:
viz_sampler_dt: 0.1                  # how dense to sample the reference trajectory (affects ONLY visualization!)
sphere_size: 0.15                     # size of spheres that differentiate between trajectories

#publishing of logged variables:
pub_log_var: false
